@startuml{images/phone.png}
scale 2
title ガラケー（フィーチャーフォン） 

[*] -> 待機中 : 電源ON
待機中 -> 発信番号入力中 : 番号キー押下
発信番号入力中 --> 発信番号入力中 : 番号キー押下
発信番号入力中 --> 発信中 : 発話キー押下[圏内]
発信番号入力中 --> 待機中 : 発話キー押下[圏外]
発信中 --> 通話中 : 電話相手発話キー押下
発信中 --> 切断中 : 電話相手終話キー押下

待機中 --> 着信中 : 着信あり
着信中 --> 通話中 : 発話キー押下[圏内]
通話中 -> 切断中 : 電話相手終話キー押下
通話中 -> 切断中 : 終話キー押下
切断中 --> 待機中 : 切断完了

着信中 --> 切断中 : 終話キー押下

note "この状態遷移は終了状態なし" as N1
@enduml
