@startuml{images/wacate.png}
scale 2
title wacate echo 

[*] -> 初期化動作中 : 電源ON
初期化動作中 -> 待機中 : 初期化完了
待機中 --> 音声認識状態 : キーワード受信[インターネット接続あり]
待機中 -> 待機中 : キーワード受信[インターネットなし]
音声認識状態 --> 音楽再生中 : 「音楽かけて」命令受信
音声認識状態 --> 待機中 : 「次の曲」命令受信
音声認識状態 --> 待機中 : 「音楽止めて」命令受信
音声認識状態 --> 待機中 : タイムアウト
音楽再生中 --> 音声再生中音声認識状態 : キーワード受信[インターネット接続あり]
音楽再生中 -> 音楽再生中 : キーワード受信[インターネットなし]
音声再生中音声認識状態 -> 音楽再生中 : 「音楽かけて」命令受信
音声再生中音声認識状態 -> 音楽再生中 : 「次の曲」命令受信
音声再生中音声認識状態 -> 待機中 : 「音楽止めて」命令受信
音声再生中音声認識状態 -> 音楽再生中 : タイムアウト
@enduml
